// Service worker: precaches every app file so the installed app runs fully
// offline. The file list and version below are generated by
// `npm run precache` (tools/update-precache.mjs) — run it after changing files.

// <precache>
const VERSION = 'dev';
const FILES = ['./', './index.html'];
// </precache>

const CACHE = `bjv-${VERSION}`;

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(FILES))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('bjv-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  // Strategy import and the casino database are online services; never cache them.
  if (url.origin !== location.origin || /^\/apps\//i.test(url.pathname)) return;
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then(hit => {
      if (hit) return hit;
      // Cache miss (partial install or eviction): fetch, and keep a good response.
      return fetch(request)
        .then(response => {
          if (response && response.ok) {
            const copy = response.clone();
            caches.open(CACHE).then(cache => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => (request.mode === 'navigate' ? caches.match('./index.html') : Response.error()));
    }),
  );
});
