// sw.js — Service Worker for Blackjack Verité Drills (local PWA mirror)
// Precaches every app file so the homescreen web-app runs fully offline
// after being served over HTTP once. Replaces the app's dead AppCache.
const CACHE = 'bjvd-v1.5.25-6';
const ASSETS = [
  './',
  './manifest.webmanifest',
  './BlackjackVeriteDrills.pdf',
  './BUZZ.mp3',
  './cards.png',
  './cvd.png',
  './DRIP2.mp3',
  './empty.png',
  './frmCount.htm',
  './frmDepth.htm',
  './frmFlash.htm',
  './frmFull.htm',
  './frmImport.htm',
  './frmMain.htm',
  './frmOptsC.htm',
  './frmOptsD.htm',
  './frmOptsF.htm',
  './frmOptsL.htm',
  './frmStrats.htm',
  './frmtabhn.htm',
  './frmtc.htm',
  './frmView.htm',
  './g.txt',
  './icons/android/bjvdhdpi.png',
  './icons/android/bjvdmdpi.png',
  './icons/android/bjvdxhdpi.png',
  './icons/android/icon.png',
  './index.html',
  './nsb/complexfunctions.js',
  './nsb/hfunc.js',
  './nsb/images/196.png',
  './nsb/images/ajax-loader.gif',
  './nsb/iscroll.js',
  './nsb/jquery.js',
  './nsb/jquery.mobile.css',
  './nsb/jquery.mobile.js',
  './nsb/nsbstyle.css',
  './res/screen/android/screen-hdpi-landscape.png',
  './res/screen/android/screen-hdpi-portrait.png',
  './res/screen/android/screen-mdpi-landscape.png',
  './res/screen/android/screen-mdpi-portrait.png',
  './res/screen/android/screen-xhdpi-landscape.png',
  './res/screen/android/screen-xhdpi-portrait.png',
  './usp2.txt',
  './usp20.txt',
  './usp22.txt',
  './usp24.txt',
  './usp25.txt',
  './usp26.txt',
  './usp27.txt',
  './usp28.txt',
  './usp29.txt',
  './usp3.txt',
  './usp30.txt',
  './usp31.txt',
  './usp32.txt',
  './usp40.txt',
  './usp42.txt',
  './usp5.txt',
  './usp50.txt',
  './usp51.txt',
  './usp52.txt',
  './usp6.txt',
  './usp60.txt',
  './usp61.txt',
  './usp7.txt',
  './usp70.txt',
  './usp71.txt',
  './usp73.txt',
  './usp74.txt',
  './usp75.txt',
  './usp76.txt',
  './usp77.txt',
  './usp80.txt',
  './usp81.txt',
  './usp82.txt',
  './usp83.txt',
  './usp90.txt',
  './usp91.txt',
  './usp96.txt',
  './usp97.txt',
  './xstw242.jpg',
  './xstw243.jpg',
  './xstw244.jpg',
  './xstw245.jpg',
  './xstw246.jpg',
  './xstw247.jpg',
  './xstw248.jpg',
  './xstw249.jpg',
  './xstw250.jpg',
  './xstw251.jpg',
  './xstw252.jpg',
  './xstw253.jpg',
  './xstw254.jpg',
  './xstw255.jpg',
  './xstw256.jpg',
  './xstw257.jpg',
  './xstw258.jpg',
  './xstw259.jpg',
  './xstw260.jpg',
  './xstw261.jpg',
  './xstw262.jpg',
  './xstw263.jpg',
  './xstw264.jpg',
  './xstw265.jpg',
  './xstw266.jpg',
  './xstw267.jpg',
  './xstw268.jpg',
  './xstw269.jpg',
  './xstw270.jpg',
  './xstw271.jpg',
  './xstw272.jpg',
  './xstw273.jpg',
  './xstw274.jpg',
  './xstw275.jpg',
  './xstw276.jpg',
  './xstw277.jpg',
  './xstw278.jpg',
  './xstw279.jpg',
  './xstw280.jpg',
  './xstw281.jpg',
  './xstw282.jpg',
  './xstw283.jpg',
  './xstw284.jpg',
  './xstw285.jpg',
  './xstw286.jpg',
  './xstw287.jpg',
  './xstw288.jpg',
  './xstw289.jpg',
  './xstw290.jpg',
  './xstw291.jpg',
  './xstw292.jpg',
  './xstw293.jpg',
  './xstw294.jpg',
  './xstw295.jpg',
  './xstw296.jpg',
  './xstw297.jpg',
  './xstw298.jpg',
  './xstw299.jpg',
  './xstw300.jpg',
  './xstw301.jpg',
  './xstw302.jpg',
  './xstw303.jpg',
  './xstw304.jpg',
  './xstw305.jpg',
  './xstw306.jpg',
  './xstw307.jpg',
  './xstw308.jpg',
  './xstw309.jpg',
  './xstw310.jpg',
  './xstw311.jpg',
  './xstw312.jpg',
  './xstw313.jpg',
  './xstw314.jpg',
  './xstw315.jpg',
  './xstw316.jpg',
  './xstw317.jpg',
  './xstw318.jpg',
  './xstw319.jpg',
  './xstw320.jpg',
  './xstw321.jpg',
  './xstw322.jpg',
  './xstw323.jpg',
  './xstw324.jpg',
  './xstw325.jpg',
  './xstw326.jpg',
  './xstw327.jpg',
  './xstw328.jpg',
  './xstw329.jpg',
  './xstw330.jpg',
  './xstw331.jpg',
  './xstw332.jpg',
  './xstw333.jpg',
  './xstw334.jpg',
  './xstw335.jpg',
  './xstw336.jpg',
  './xstw337.jpg',
  './xstw338.jpg',
  './xstw339.jpg',
  './xstw340.jpg',
  './xstw341.jpg',
  './xstw342.jpg',
  './xstw343.jpg',
  './xstw344.jpg',
  './xstw345.jpg',
  './xstw346.jpg',
  './xstw347.jpg',
  './xstw348.jpg',
  './xstw349.jpg',
  './xstw350.jpg',
  './xstw351.jpg',
  './xstw366.jpg',
  './xstw367.jpg',
  './xstw368.jpg',
  './xstw369.jpg',
  './xstw370.jpg',
  './xstw371.jpg',
  './xstw372.jpg',
  './xstw373.jpg',
  './xstw374.jpg',
  './xstw375.jpg',
  './xstw376.jpg',
  './xstw377.jpg',
  './xstw378.jpg',
  './xstw379.jpg',
  './xstw380.jpg',
  './xstw381.jpg',
  './xstw382.jpg',
  './xstw383.jpg',
  './xstw384.jpg',
  './xstw385.jpg',
  './xstw386.jpg',
  './xstw387.jpg',
  './xstw388.jpg',
  './xstw389.jpg',
  './xstw390.jpg',
  './xstw391.jpg',
  './xstw392.jpg',
  './xstw393.jpg',
  './xstw394.jpg',
  './xstw395.jpg',
  './xstw396.jpg',
  './xstw397.jpg',
  './xstw398.jpg',
  './xstw399.jpg',
  './xstw400.jpg',
  './xstw401.jpg',
  './xstw402.jpg',
  './xstw403.jpg',
  './xstw404.jpg',
  './xstw405.jpg',
  './xstw406.jpg',
  './xstw407.jpg',
  './xstw408.jpg',
  './xstw409.jpg',
  './xstw410.jpg',
  './xstw411.jpg',
  './xstw412.jpg',
  './xstw413.jpg',
  './xstw414.jpg',
  './xstw415.jpg',
  './xstw416.jpg',
  './xstw417.jpg',
  './xstw418.jpg',
  './xstw419.jpg',
  './xstw420.jpg',
  './xstw421.jpg',
  './xstw422.jpg',
  './xstw423.jpg',
  './xstw424.jpg',
  './xstw425.jpg',
  './xstw426.jpg',
  './xstw427.jpg',
  './xstw428.jpg',
  './xstw429.jpg',
  './xstw430.jpg',
  './xstw431.jpg',
  './xstw432.jpg',
  './xstw433.jpg',
  './xstw434.jpg',
  './xstw435.jpg',
  './xstw436.jpg',
  './xstw437.jpg',
  './xstw438.jpg',
  './xstw439.jpg',
  './xstw440.jpg',
  './xstw441.jpg',
  './xstw442.jpg',
  './xstw443.jpg',
  './xstw444.jpg',
  './xstw445.jpg',
  './xstw446.jpg',
  './xstw447.jpg',
];

self.addEventListener('install', (e) => {
  // Cache everything, then activate immediately.
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  // Drop caches from older versions and take control of open pages.
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  // Cache-first: the app is fully static, so a cache hit is always correct offline.
  e.respondWith(
    caches.match(req).then((hit) => {
      if (hit) return hit;
      // Cache miss (partial install, version-bump gap, or storage eviction): fetch
      // and write a good response back so the file survives the next offline launch.
      return fetch(req).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => {
        // Offline and uncached: for a page navigation, fall back to the app shell.
        if (req.mode === 'navigate') return caches.match('./');
        return Response.error();
      });
    })
  );
});
